### ISSUE TITLE
关于httpServer.cpp172行

### ISSUE THREAD

**Issue by smi1lee** [tinoryj/Server#2]
if ( (!strcasecmp(method, "GET")) && (!strcasecmp(method, "POST")) )
这一行我觉得您本来想表达的意思是既不是get方法也不是post方法，
strcasecmp(method, "GET") 表示如果是get方法，为0，你前面再加 ！ 的话逻辑是有点问题的

**Comment by tinoryj** [comment]
非常感谢，已修正
